name: My Workflow
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
        
      - name: Install mypy
        run: |
          pip install mypy

      - name: Add mypy annotator
        uses: pr-annotators/mypy-pr-annotator@master

      - name: Run mypy
        run: |
          mypy demos/
